Remove v13 manifest and update v12 to have `limit` and `order_by`
dbt-labs/schemas.getdbt.com pull request #65
Opened 2024-10-12 03:49 UTC by QMalcolm

Originally adding `limit` and `order_by` was done by https://github.com/dbt-labs/schemas.getdbt.com/pull/49, which added the v13 manifest. However, as these fields are additive and have default values, they aren't breaking changes. Thus, here we're adding them to the v12 manifest. This is in support of the currently open dbt-core PR https://github.com/dbt-labs/dbt-core/pull/10532.

Note this also _drops_ the `vars` field from a few objects. It was originally added to support changes in core (https://github.com/dbt-labs/dbt-core/pull/10793). However, those changes were reverted in core (https://github.com/dbt-labs/dbt-core/pull/10813). Since `vars` as a field never went out in a GA release of dbt-core, it is safe for us to drop it.

2024-10-14 20:31 UTC, aranke requested changes
Hmm, do we want to unpublish `v13` **in this PR**?

Can we scope this PR to just `update v12 to have limit and order_by` and create another PR for deprecating v13?

2024-10-14 20:32 UTC, QMalcolm commented
> Hmm, do we want to unpublish `v13` in this PR?
> 
> Can we scope this PR to just `update v12 to have limit and order_by`?

We do want to unpublish v13

2024-10-15 16:58 UTC, QMalcolm commented
Rebasing to drop commit [bea8616](https://github.com/dbt-labs/schemas.getdbt.com/pull/65/commits/bea861698e697ec295e7aaff49e1e7df65eb4d3a) (the revert of v13), as that is will now be handled by #66

2024-10-15 17:08 UTC, aranke approved these changes

2024-10-15 19:26 UTC, merged